ADMIXTOOOLS version 4.1  5/15/16 (for Linux and Mac)

Best is to recompile on your system. 

You will need to be able to link GNU Scientific library(gsl) , BLAS and pprpbably lapack.  
This Makefile expects opeenblas but other versions of BLAS should be OK.  Edit the Makefile 
appropriately.

cd src;  make clobber; make all; make install.  Eexcutables will be in ../bin
A copy of executables made at Harvard (HMS) is in ../harvardbin, but these are dynamically loaded
and likely will fail to execute on tour system.  

A Makefile that worked for a Mac (El Capitan) is in src/Makefile.mac

Nick Patterson
