#!/usr/bin/perl  -w 

use Getopt::Std ;
getopts('a:b:o:',\%opts) ;

$fa = $opts{"a"} ; 
$fb = $opts{"b"} ; 
$fout = $opts{"o"} ; 

die "no -a parameter\n" unless (defined $fa) ;
die "no -b parameter\n" unless (defined $fb) ;

open (I1, "$fa") || die "can't open $fa\n" ; 
open (I2, "$fb") || die "can't open $fa\n" ; 

$maxa = -1 ; 
foreach $line (<I1>) { 
 ($a, $w, $v) = split " ", $line ; 
 next if ($a =~ /\#/) ;
 next unless (defined $v) ; 
 $WA[$a] = $w ; 
 $VA[$a] = $v ; 
}
foreach $line (<I2>) { 
 ($a, $w, $v) = split " ", $line ; 
 next if ($a =~ /\#/) ;
 next unless (defined $v) ; 
 $WB[$a] = $w ; 
 $VB[$a] = $v ; 
 $maxa = $a ; 
}
$T1 = "/tmp/t1.$$" ;
open (Y1, ">$T1") ; 

foreach $a (0..$maxa) { 
 $wa = $WA[$a] ;
 $wb = $WB[$a] ;
 $va = $VA[$a] ;
 $vb = $VB[$a] ;
 die "mismatched weights: line index $a\n" if ($wa != $wb) ; 
 printf Y1 "%d %d %12.6f\n", $a, $wa, $va - $vb ; 
}
close Y1 ; 
system "mkpretty $T1 $fout" if (defined $fout) ; 
printf "##jackknife difference $fa - $fb\n" ;
system "simpjack2 -i $T1 -v" ; 
